const BloodDonationClubMembers = [
    {
        id : 1, 
        name : 'Emran Hasan', 
        age : 38,
        blood_group : 'O+', 
        location : 'Mirpur',
        cell : '01794430908',
        donation_history : [{
            blood_taker_name : 'Jamal Khan',
            number_of_donation : 4,
        },{
            blood_taker_name: 'Imrul Kayes'
        },{
            blood_taker_name: 'Azaharul Islam'
        }],
        last_donate : 142,
    },
    {
        id : 2, 
        name : 'Mahbubur Rahman', 
        age : 30,
        blood_group : 'A+', 
        location : 'Dholaipar',
        cell : '01794430607',
        donation_history : [{
            blood_taker_name : 'Rahim Uddin',
            number_of_donation : 2,
        }],
        last_donate : 20,
    },
    {
        id : 3, 
        name : 'Sirajum Munir', 
        age : 25,
        blood_group : 'B+', 
        location : 'Dhanmondi',
        cell : '01594450805',
        donation_history : [{
            blood_taker_name : 'Abid Hasan',
            number_of_donation : 6,
        }],
        last_donate : 70,
    },
    {
        id : 4, 
        name : 'Rezaul Hasan', 
        age : 52,
        blood_group : 'A+', 
        location : 'Mirpur',
        cell : '01954430703',
        donation_history : [{
            blood_taker_name : 'Emran Hasan',
            number_of_donation : 1,
        }],
        last_donate : 52,
    },
    {
        id : 5, 
        name : 'Abedur Reza', 
        age : 15,
        blood_group : 'O-', 
        location : 'Uttara',
        cell : '01694430123',
        donation_history : [{
            blood_taker_name : 'Melon Khan',
            number_of_donation : 10,
        }],
        last_donate : 80,
    },
    {
        id : 6, 
        name : 'Azaharul Islam', 
        age : 42,
        blood_group : 'O-', 
        location : 'Mirpur',
        cell : '01894430456',
        donation_history : [{
            blood_taker_name : 'Bipro',
            number_of_donation : 5,
        }],
        last_donate : 152,
    },
    {
        id : 7, 
        name : 'Zakir Hossain', 
        age : 28,
        blood_group : 'B+', 
        location : 'Uttara',
        cell : '01524430789',
        donation_history : [{
            blood_taker_name : 'Shaikot Islam',
            number_of_donation : 8,
        }],
        last_donate : 60,
    },
    {
        id : 8, 
        name : 'Tania Sultana', 
        age : 23,
        blood_group : 'B+', 
        location : 'Dhanmondi',
        cell : '01694430806',
        donation_history : [{
            blood_taker_name : 'Azhar Uddin',
            number_of_donation : 2,
        }],
        last_donate : 72,
    },
    {
        id : 9, 
        name : 'Nur E Modina', 
        age : 18,
        blood_group : 'B-', 
        location : 'Badda',
        cell : '01915301234',
        donation_history : [{
            blood_taker_name : 'Rahim Khan',
            number_of_donation : 5,
        }],
        last_donate : 90,
    },
    {
        id : 10, 
        name : 'Tarek Hasan Khan', 
        age : 36,
        blood_group : 'B-', 
        location : 'Dhanmondi',
        cell : '01594439874',
        donation_history : [{
            blood_taker_name : 'Mahmud',
            number_of_donation : 9,
        }],
        last_donate : 10,
    },
    {
        id : 11, 
        name : 'Tanvir Hasan', 
        age : 29,
        blood_group : 'A-', 
        location : 'Mirpur',
        cell : '01895563214',
        donation_history : [{
            blood_taker_name : 'Apon Bissas',
            number_of_donation : 1,
        }],
        last_donate : 140,
    },
    {
        id : 12, 
        name : 'Sujit Kumar', 
        age : 62,
        blood_group : 'O-', 
        location : 'Uttara',
        cell : '01524430906',
        donation_history : [{
            blood_taker_name : 'Abedur Reza',
            number_of_donation : 6,
        }],
        last_donate : 30,
    },
    {
        id : 13, 
        name : 'Sajjad Khan', 
        age : 45,
        blood_group : 'A-', 
        location : 'Badda',
        cell : '01589443092',
        donation_history : [{
            blood_taker_name : 'Kamrul Hasan',
            number_of_donation : 7,
        }],
        last_donate : 185,
    },
    {
        id : 14, 
        name : 'Swapon Kumar', 
        age : 21,
        blood_group : 'O+', 
        location : 'Dhanmondi',
        cell : '01624430859',
        donation_history : [{
            blood_taker_name : 'Emran Hasan',
            number_of_donation : 12,
        }],
        last_donate : 5,
    },
    {
        id : 15, 
        name : 'Shoriful Islam', 
        age : 26,
        blood_group : 'O-', 
        location : 'Dhanmondi',
        cell : '018594430623',
        donation_history : [{
            blood_taker_name : 'Torikul Hasan',
            number_of_donation : 4,
        }],
        last_donate : 72,
    },
    {
        id : 16, 
        name : 'Azimul Haque Khan', 
        age : 32,
        blood_group : 'B+', 
        location : 'Mirpur',
        cell : '02364430789',
        donation_history : [{
            blood_taker_name : 'Ariful Haque',
            number_of_donation : 5,
        }],
        last_donate : 150,
    },
    {
        id : 17, 
        name : 'Hasan Tarek', 
        age : 42,
        blood_group : 'B-', 
        location : 'Uttara',
        cell : '01894430852',
        donation_history : [{
            blood_taker_name : 'Emran Hasan',
            number_of_donation : 1,
        }],
        last_donate : 200,
    },
    {
        id : 18, 
        name : 'Farzan Ali', 
        age : 45,
        blood_group : 'O+', 
        location : 'Badda',
        cell : '01814430741',
        donation_history : [{
            blood_taker_name : 'Kamrul Hasan',
            number_of_donation : 9,
        }],
        last_donate : 124,
    },
    {
        id : 19, 
        name : 'Chandan Kumar', 
        age : 38,
        blood_group : 'O-', 
        location : 'Dhanmondi',
        cell : '01534430963',
        donation_history : [{
            blood_taker_name : 'Abid Hasan',
            number_of_donation : 2,
        }],
        last_donate : 130,
    },
    {
        id : 20, 
        name : 'Shoyeb Chowdhury', 
        age : 52,
        blood_group : 'A+', 
        location : 'Dhanmondi',
        cell : '01894430852',
        donation_history : [{
            blood_taker_name : 'Kamal Hasan',
            number_of_donation : 3,
        }],
        last_donate : 200,
    },
]